;; -*- mode: lisp; -*-
;; Filename: ami.lisp
;; Description: 
;; Author: User Alex
;; 
;; Maintainer: 
;; Created: Sat May 12 13:20:48 2012 (+0400)
;; Version: 
;; Last-Updated: Sun May 13 23:34:57 2012 (+0400)
;;           By: alex
;;     Update #: 85
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(in-package :cl-user)

(defpackage ami
  (:use :cl :asdf :iolib)
  (:export :ami-session
	   :send-action
	   :%make-ami-session
	   :%make-ami-action
	   :get-respond
	   :close-session))

(in-package :ami)


(defun string-split (devider string)
  (if (null (position devider string))
      (list (string-trim " " string))
      (append  (list (subseq string 0 (position devider string)))
               (string-split devider (subseq string (+ 1 (position devider string)))))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Action

(defstruct (ami-action (:constructor %make-ami-action)
		       (:conc-name ami-action-))
  (name nil :type simple-array)
  (id nil :type fixnum)
  (argv nil :type list))

(defmethod print-object ((object ami-action) (stream stream))
  (print-unreadable-object (object stream :type t :identity t)
    (format stream "~s ID:~a" (ami-action-name object) (ami-action-id object))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Session

(defstruct (ami-session (:constructor %make-ami-session)
		(:conc-name ami-session-))
  ;; Hostname with AMI interface. 
  (host nil :type (or ipv4-address ipv6-address))
  ;; AMI port
  (port nil :type fixnum)
  (username nil :type simple-array)
  (secret nil :type simple-array)
  ;; not-NULL If you need to subscribe to events being generated by
  ;; Asterisk.
  (events nil :type boolean)
  (socket nil))

(defmethod print-object ((object ami-session) (stream stream))
  (print-unreadable-object (object stream :type t :identity t)
    (format stream "~a:~a" (ami-session-host object) (ami-session-port object))))

(defmethod send-action ((object ami-session) (action ami-action))
  (let  ((socket (ami-session-socket object)))
    (format socket "Action: ~a~%" (ami-action-name action))
    (format socket "ActionID: ~a~%" (ami-action-id action))
    ;; Write Keys
    (dolist (key/value (ami-action-argv action))
      (format socket "~a: ~a~%" (car key/value) (cdr key/value)))
    (finish-output socket)))

(defmethod get-respond ((object ami-session))
  (let ((result '()) (socket (ami-session-socket object)))
    (do ((line (read-line socket nil "")
	       (read-line socket nil "")))
	((string= line ""))
      (format t "~S"  (string-split #\: line))
      (push (string-split #\: line) result))
    (values result)))

(defmethod close-session ((object ami-session))
  (close (ami-session-socket object)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; ami.lisp ends here
